//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MR_Reporting_System_Data_Service.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public Agent()
        {
            this.Distributers = new HashSet<Distributer>();
            this.Docotors = new HashSet<Docotor>();
            this.Drugs = new HashSet<Drug>();
            this.AgentDistributers = new HashSet<AgentDistributer>();
            this.AgentAreas = new HashSet<AgentArea>();
            this.AgentDrugs = new HashSet<AgentDrug>();
            this.AgentHospitals = new HashSet<AgentHospital>();
            this.AgentPharmacies = new HashSet<AgentPharmacy>();
            this.Agent1 = new HashSet<Agent>();
            this.Areas = new HashSet<Area>();
            this.Visits = new HashSet<Visit>();
            this.Visits1 = new HashSet<Visit>();
            this.Hospitals = new HashSet<Hospital>();
            this.Locations = new HashSet<Location>();
        }
    
        public int id { get; set; }
        public string userName { get; set; }
        public string passWord { get; set; }
        public string ContactName { get; set; }
        public Nullable<int> postionId { get; set; }
        public Nullable<int> areaId { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public Nullable<int> groupId { get; set; }
        public Nullable<double> salary { get; set; }
        public Nullable<int> noOfVisits { get; set; }
        public Nullable<int> supervisorId { get; set; }
        public string Code { get; set; }
        public string userType { get; set; }
    
        public virtual ICollection<Distributer> Distributers { get; set; }
        public virtual ICollection<Docotor> Docotors { get; set; }
        public virtual ICollection<Drug> Drugs { get; set; }
        public virtual ICollection<AgentDistributer> AgentDistributers { get; set; }
        public virtual ICollection<AgentArea> AgentAreas { get; set; }
        public virtual ICollection<AgentDrug> AgentDrugs { get; set; }
        public virtual ICollection<AgentHospital> AgentHospitals { get; set; }
        public virtual ICollection<AgentPharmacy> AgentPharmacies { get; set; }
        public virtual ICollection<Agent> Agent1 { get; set; }
        public virtual Agent Agent2 { get; set; }
        public virtual Area Area { get; set; }
        public virtual DefaultList DefaultList { get; set; }
        public virtual Group Group { get; set; }
        public virtual ICollection<Area> Areas { get; set; }
        public virtual ICollection<Visit> Visits { get; set; }
        public virtual ICollection<Visit> Visits1 { get; set; }
        public virtual ICollection<Hospital> Hospitals { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
    }
}
