//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MR_Reporting_System_Data_Service.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.Agents = new HashSet<Agent>();
            this.AgentAreas = new HashSet<AgentArea>();
            this.Distributers = new HashSet<Distributer>();
            this.Docotors = new HashSet<Docotor>();
            this.Hospitals = new HashSet<Hospital>();
            this.Pharmacies = new HashSet<Pharmacy>();
        }
    
        public int id { get; set; }
        public Nullable<int> locationId { get; set; }
        public string title { get; set; }
        public Nullable<int> deletedBy { get; set; }
    
        public virtual ICollection<Agent> Agents { get; set; }
        public virtual Agent Agent { get; set; }
        public virtual ICollection<AgentArea> AgentAreas { get; set; }
        public virtual Location Location { get; set; }
        public virtual ICollection<Distributer> Distributers { get; set; }
        public virtual ICollection<Docotor> Docotors { get; set; }
        public virtual ICollection<Hospital> Hospitals { get; set; }
        public virtual ICollection<Pharmacy> Pharmacies { get; set; }
    }
}
