//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MR_Reporting_System_Data_Service.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Docotor
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> specializeId { get; set; }
        public Nullable<bool> isMorning { get; set; }
        public string address { get; set; }
        public Nullable<int> areaId { get; set; }
        public Nullable<int> classTypeId { get; set; }
        public Nullable<int> noOfVisits { get; set; }
        public string phone { get; set; }
        public string telephone { get; set; }
        public string email { get; set; }
        public string code { get; set; }
        public Nullable<int> deletedBy { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Area Area { get; set; }
        public virtual DefaultList DefaultList { get; set; }
        public virtual DefaultList DefaultList1 { get; set; }
    }
}
