//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MR_Reporting_System_Data_Service.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drug
    {
        public Drug()
        {
            this.AgentDrugs = new HashSet<AgentDrug>();
            this.Visits = new HashSet<Visit>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string code { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> sectionId { get; set; }
        public string notes { get; set; }
        public Nullable<int> companyId { get; set; }
        public Nullable<int> deletedBy { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual ICollection<AgentDrug> AgentDrugs { get; set; }
        public virtual Company Company { get; set; }
        public virtual DefaultList DefaultList { get; set; }
        public virtual ICollection<Visit> Visits { get; set; }
    }
}
