//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MR_Reporting_System_Data_Service.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pharmacy
    {
        public Pharmacy()
        {
            this.AgentPharmacies = new HashSet<AgentPharmacy>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> areaId { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string ownerName { get; set; }
        public string ownerPhone { get; set; }
    
        public virtual ICollection<AgentPharmacy> AgentPharmacies { get; set; }
        public virtual Area Area { get; set; }
    }
}
