//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MR_Reporting_System_Data_Service.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int id { get; set; }
        public Nullable<int> agantId { get; set; }
        public Nullable<int> drugsId { get; set; }
        public Nullable<int> typeId { get; set; }
        public Nullable<int> visitTo { get; set; }
        public Nullable<System.DateTime> visitDate { get; set; }
        public Nullable<System.TimeSpan> duration { get; set; }
        public string description { get; set; }
        public Nullable<bool> isMorning { get; set; }
        public string notes { get; set; }
        public Nullable<int> lastEditBy { get; set; }
        public Nullable<System.DateTime> lastEditDate { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Agent Agent1 { get; set; }
        public virtual DefaultList DefaultList { get; set; }
        public virtual Drug Drug { get; set; }
    }
}
