//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MR_Reporting_System_Data_Context.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agents
    {
        public Agents()
        {
            this.AgentAreas = new HashSet<AgentAreas>();
            this.AgentDistributers = new HashSet<AgentDistributers>();
            this.AgentDrugs = new HashSet<AgentDrugs>();
            this.AgentHospitals = new HashSet<AgentHospitals>();
            this.AgentPharmacies = new HashSet<AgentPharmacies>();
            this.Agents1 = new HashSet<Agents>();
            this.Areas1 = new HashSet<Areas>();
            this.Distributers = new HashSet<Distributers>();
            this.Docotors = new HashSet<Docotors>();
            this.Drugs = new HashSet<Drugs>();
            this.Hospitals = new HashSet<Hospitals>();
            this.Locations = new HashSet<Locations>();
            this.Orders = new HashSet<Orders>();
            this.Orders1 = new HashSet<Orders>();
            this.Orders2 = new HashSet<Orders>();
            this.Visits = new HashSet<Visits>();
            this.Visits1 = new HashSet<Visits>();
        }
    
        public int id { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public string ContactName { get; set; }
        public Nullable<int> PostionId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<double> Salary { get; set; }
        public Nullable<int> NoOfVisits { get; set; }
        public Nullable<int> SupervisorId { get; set; }
        public string Code { get; set; }
        public string UserType { get; set; }
    
        public virtual ICollection<AgentAreas> AgentAreas { get; set; }
        public virtual ICollection<AgentDistributers> AgentDistributers { get; set; }
        public virtual ICollection<AgentDrugs> AgentDrugs { get; set; }
        public virtual ICollection<AgentHospitals> AgentHospitals { get; set; }
        public virtual ICollection<AgentPharmacies> AgentPharmacies { get; set; }
        public virtual ICollection<Agents> Agents1 { get; set; }
        public virtual Agents Agents2 { get; set; }
        public virtual Areas Areas { get; set; }
        public virtual DefaultLists DefaultLists { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual ICollection<Areas> Areas1 { get; set; }
        public virtual ICollection<Distributers> Distributers { get; set; }
        public virtual ICollection<Docotors> Docotors { get; set; }
        public virtual ICollection<Drugs> Drugs { get; set; }
        public virtual ICollection<Hospitals> Hospitals { get; set; }
        public virtual ICollection<Locations> Locations { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<Orders> Orders1 { get; set; }
        public virtual ICollection<Orders> Orders2 { get; set; }
        public virtual ICollection<Visits> Visits { get; set; }
        public virtual ICollection<Visits> Visits1 { get; set; }
    }
}
