//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MR_Reporting_System_Data_Context.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Areas
    {
        public Areas()
        {
            this.AgentAreas = new HashSet<AgentAreas>();
            this.Agents = new HashSet<Agents>();
            this.Distributers = new HashSet<Distributers>();
            this.Docotors = new HashSet<Docotors>();
            this.Hospitals = new HashSet<Hospitals>();
            this.Pharmacies = new HashSet<Pharmacies>();
        }
    
        public int Id { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string Title { get; set; }
        public Nullable<int> DeletedBy { get; set; }
    
        public virtual ICollection<AgentAreas> AgentAreas { get; set; }
        public virtual ICollection<Agents> Agents { get; set; }
        public virtual Agents Agents1 { get; set; }
        public virtual Locations Locations { get; set; }
        public virtual ICollection<Distributers> Distributers { get; set; }
        public virtual ICollection<Docotors> Docotors { get; set; }
        public virtual ICollection<Hospitals> Hospitals { get; set; }
        public virtual ICollection<Pharmacies> Pharmacies { get; set; }
    }
}
