//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MR_Reporting_System_Data_Context.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefaultLists
    {
        public DefaultLists()
        {
            this.Agents = new HashSet<Agents>();
            this.Docotors = new HashSet<Docotors>();
            this.Docotors1 = new HashSet<Docotors>();
            this.Drugs = new HashSet<Drugs>();
            this.Hospitals = new HashSet<Hospitals>();
            this.Orders = new HashSet<Orders>();
            this.Visits = new HashSet<Visits>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public Nullable<int> Action { get; set; }
    
        public virtual ICollection<Agents> Agents { get; set; }
        public virtual ICollection<Docotors> Docotors { get; set; }
        public virtual ICollection<Docotors> Docotors1 { get; set; }
        public virtual ICollection<Drugs> Drugs { get; set; }
        public virtual ICollection<Hospitals> Hospitals { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<Visits> Visits { get; set; }
    }
}
