//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MR_Reporting_System_Data_Context.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drugs
    {
        public Drugs()
        {
            this.AgentDrugs = new HashSet<AgentDrugs>();
            this.ordersItems = new HashSet<ordersItems>();
            this.Visits = new HashSet<Visits>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> SectionId { get; set; }
        public string Notes { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> DeletedBy { get; set; }
    
        public virtual ICollection<AgentDrugs> AgentDrugs { get; set; }
        public virtual Agents Agents { get; set; }
        public virtual Companies Companies { get; set; }
        public virtual DefaultLists DefaultLists { get; set; }
        public virtual ICollection<ordersItems> ordersItems { get; set; }
        public virtual ICollection<Visits> Visits { get; set; }
    }
}
