//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MR_Reporting_System_Data_Context.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drug
    {
        public Drug()
        {
            this.AgentDrugs = new HashSet<AgentDrug>();
            this.ordersItems = new HashSet<ordersItem>();
            this.Visits = new HashSet<Visit>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> SectionId { get; set; }
        public string Notes { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> DeletedBy { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual ICollection<AgentDrug> AgentDrugs { get; set; }
        public virtual Company Company { get; set; }
        public virtual DefaultList DefaultList { get; set; }
        public virtual ICollection<ordersItem> ordersItems { get; set; }
        public virtual ICollection<Visit> Visits { get; set; }
    }
}
