//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MR_Reporting_System_Data_Context.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groups
    {
        public Groups()
        {
            this.Agents = new HashSet<Agents>();
            this.GroupPermissions = new HashSet<GroupPermissions>();
        }
    
        public int Id { get; set; }
        public string GroupName { get; set; }
    
        public virtual ICollection<Agents> Agents { get; set; }
        public virtual ICollection<GroupPermissions> GroupPermissions { get; set; }
    }
}
