//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MR_Reporting_System_Data_Context.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupPermissions
    {
        public int Id { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> PermissionCode { get; set; }
        public Nullable<bool> Value { get; set; }
    
        public virtual Groups Groups { get; set; }
    }
}
