//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MR_Reporting_System_Data_Context.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospitals
    {
        public Hospitals()
        {
            this.AgentHospitals = new HashSet<AgentHospitals>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> Type { get; set; }
        public string Code { get; set; }
        public Nullable<int> DeletedBy { get; set; }
    
        public virtual ICollection<AgentHospitals> AgentHospitals { get; set; }
        public virtual Agents Agents { get; set; }
        public virtual Areas Areas { get; set; }
        public virtual DefaultLists DefaultLists { get; set; }
    }
}
