//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MR_Reporting_System_Data_Context.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.Areas = new HashSet<Area>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> DeletedBy { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual ICollection<Area> Areas { get; set; }
    }
}
