//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MR_Reporting_System_Data_Context.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedicalTechnoEntities : DbContext
    {
        public MedicalTechnoEntities()
            : base("name=MedicalTechnoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agent> Agents { get; set; }
        public virtual DbSet<AgentArea> AgentAreas { get; set; }
        public virtual DbSet<AgentDistributer> AgentDistributers { get; set; }
        public virtual DbSet<AgentDrug> AgentDrugs { get; set; }
        public virtual DbSet<AgentHospital> AgentHospitals { get; set; }
        public virtual DbSet<AgentPharmacie> AgentPharmacies { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<DefaultList> DefaultLists { get; set; }
        public virtual DbSet<Distributer> Distributers { get; set; }
        public virtual DbSet<Docotor> Docotors { get; set; }
        public virtual DbSet<Drug> Drugs { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<GroupPermission> GroupPermissions { get; set; }
        public virtual DbSet<Hospital> Hospitals { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<ordersItem> ordersItems { get; set; }
        public virtual DbSet<Pharmacy> Pharmacies { get; set; }
        public virtual DbSet<Visit> Visits { get; set; }
    }
}
