//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MR_Reporting_System_Data_Context.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedicalTechnoEntities : DbContext
    {
        public MedicalTechnoEntities()
            : base("name=MedicalTechnoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgentAreas> AgentAreas { get; set; }
        public virtual DbSet<AgentDistributers> AgentDistributers { get; set; }
        public virtual DbSet<AgentDrugs> AgentDrugs { get; set; }
        public virtual DbSet<AgentHospitals> AgentHospitals { get; set; }
        public virtual DbSet<AgentPharmacies> AgentPharmacies { get; set; }
        public virtual DbSet<Agents> Agents { get; set; }
        public virtual DbSet<Areas> Areas { get; set; }
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<DefaultLists> DefaultLists { get; set; }
        public virtual DbSet<Distributers> Distributers { get; set; }
        public virtual DbSet<Docotors> Docotors { get; set; }
        public virtual DbSet<Drugs> Drugs { get; set; }
        public virtual DbSet<GroupPermissions> GroupPermissions { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<Hospitals> Hospitals { get; set; }
        public virtual DbSet<Locations> Locations { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<ordersItems> ordersItems { get; set; }
        public virtual DbSet<Pharmacies> Pharmacies { get; set; }
        public virtual DbSet<Visits> Visits { get; set; }
    }
}
