//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MR_Reporting_System_Data_Context.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.ordersItems = new HashSet<ordersItem>();
        }
    
        public int id { get; set; }
        public Nullable<int> orderTo { get; set; }
        public Nullable<int> orderTypeId { get; set; }
        public Nullable<int> agentId { get; set; }
        public string subject { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public Nullable<System.DateTime> estimateDate { get; set; }
        public Nullable<System.DateTime> deliverdDate { get; set; }
        public Nullable<bool> supervisorApprove { get; set; }
        public Nullable<bool> isDeliverd { get; set; }
        public Nullable<System.DateTime> supervisorDate { get; set; }
        public Nullable<int> noOfItems { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<double> netTotal { get; set; }
        public Nullable<int> lastEditBy { get; set; }
        public Nullable<System.DateTime> lastEditDate { get; set; }
        public Nullable<int> deletedBy { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Agent Agent1 { get; set; }
        public virtual Agent Agent2 { get; set; }
        public virtual DefaultList DefaultList { get; set; }
        public virtual ICollection<ordersItem> ordersItems { get; set; }
    }
}
