//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MR_Reporting_System_Data_Context.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordersItem
    {
        public int id { get; set; }
        public string description { get; set; }
        public string itemCode { get; set; }
        public Nullable<double> unitPrice { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<int> drugsId { get; set; }
    
        public virtual Drug Drug { get; set; }
    }
}
