//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MR_Reporting_System_Data_Context.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pharmacy
    {
        public Pharmacy()
        {
            this.AgentPharmacies = new HashSet<AgentPharmacie>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string OwnerName { get; set; }
        public string OwnerPhone { get; set; }
        public string code { get; set; }
    
        public virtual ICollection<AgentPharmacie> AgentPharmacies { get; set; }
        public virtual Area Area { get; set; }
    }
}
